version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: pg
      POSTGRES_USER: yt
      POSTGRES_PASSWORD: ytpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
  yt_files:  # defined here for app, not used by db